## YAML Template.
---
#[39,38,37,36]
EffectSlots: 
    39:
        Filter: HELMET
    38:
        Filter: CHEST
    37:
        Filter: LEGS
    36:
        Filter: BOOTS
    InHand:
        Filter: [SWORD,BOW,TOOL]
        