## YAML Template.
---
#[39,38,37,36]
EffectSlots: 
    39:
        Filter: HELMET
    38:
        Filter: CHEST
    37:
        Filter: LEGS
    36:
        Filter: BOOTS
    InHand:
        Filter: [SWORD,BOW,TOOL]
Effects:
    Burn:
        EffectId: BurnEffect
        Name: '%1$+d%% Burn-Chance (%2$d sec)'
        BurnChance: 20
        BurnDuration: max5
    Level:
        EffectId: LevelEffect
        Name: 'Level %1$s'
        Level: max5
    Dodge:
        EffectId: DodgeEffect
        DamageType: ENTITY_ATTACK
        Name: '%1$+d%% Dodge'
        DodgeChance: 10
    FireResist:
        EffectId: ResistanceEffect
        DamageType: FIRE
        Name: '%1$+.1f Fire Resistance'
        ResistAmount: 0.5
    WitherResist:
        EffectId: ResistanceEffect
        DamageType: WITHER
        Name: '%1$+.1f Wither Resistance'
        ResistAmount: 0.5
    PoisonResist:
        EffectId: ResistanceEffect
        DamageType: POISON
        Name: '%1$+.1f Poison Resistance'
        ResistAmount: 0.5
    Health:
        EffectId: HealthEffect
        Name: '+%1$d Health'
        Health: 10