#Available predefined groups:
#- HELMET
#- CHEST
#- LEGS
#- BOOTS
#- ARMOR
#- SWORD
#- BOW
#- HOE
#- PICKAXE
#- SPADE
#- ROD
#- TOOL
#- ANY
#Any of these are valid as a filter as well as any Material
#Example:
#1:
#   Filter: - HELMET
#           - DIAMOND_SWORD
#This filter will activate an item in slot 1 if it's a Helmet or a Diamond Sword 
EffectSlots: 
    39:
        Filter: HELMET
    38:
        Filter: CHEST
    37:
        Filter: LEGS
    36:
        Filter: BOOTS
    InHand:
        Filter: [SWORD,BOW,TOOL]
        