## YAML Template.
---
name: ItemEffects
author: McDjuady
main: com.googlemail.mcdjuady.itemeffects.ItemEffects
version: 0.9-SNAPSHOT
commands:
    ItemEffects:
        usage: |
               /<command> enchant {Effect} [Parameters]
               /<command> remove {Effect}
        aliases: [ie]